name: 'sitkoru/semantic-release-action'
description: 'Action to run semantic-release with deps for sitkoru/semantic-release-config preinstalled'
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - name: Install node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"
    - name: Run semantic-release
      run: npx --package @sitkoru/semantic-release-config --package @semantic-release/github@8 --package semantic-release@19 -y semantic-release
      shell: bash
